### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by Pamphilemkp**
Create a new Rails API app called 'hello-rails-back-end'.
    Initialize your project with Git.
    Make sure that your project has a Postgres database set up.
    Create a table for storing your messages and create 5 different greetings.
    Create an API endpoint that selects a random greeting from your table (you will need a controller with an action an rails route).

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Pamphilemkp 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper Gitflow, and does not have the key features and future features sections in your readme, Kindly add link of your frontend repository in your readme 👍🏿 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Pamphilemkp** [comment]
Hi @prolajumokeoni  thank you for raising out this point, i have completely forgotten about it, but the gitflow has been successfully updated

**Review by cynthiainga — COMMENTED** [review]
Hi @Pamphilemkp, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a link to the frontend part. As mentioned by the previous reviewer kindly add the link to the frontend part in your README file 😉.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Pamphilemkp** [comment]
Hi @cynthiainga  i am already on that 😄 😄  , will soon be done

**Pull request closed without merging**
